use anyhow::Result;
use peeldoc_models::*;
use peeldoc_parser::Parser;
use peeldoc_ssg::Ssg;
use std::fs;
use std::path::Path;
use walkdir::WalkDir;

#[tokio::main]
async fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 3 {
        println!("Usage: peeldoc <input_dir> <output_dir>");
        return Ok(());
    }

    let input_dir = &args[1];
    let output_dir = &args[2];

    println!("Scanning {}...", input_dir);

    let parser = Parser::new();
    let mut modules = Vec::new();

    for entry in WalkDir::new(input_dir).into_iter().filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.extension().map(|s| s == "pel").unwrap_or(false) {
            let content = fs::read_to_string(path)?;
            let path_str = path.to_string_lossy();
            println!("  Parsing {}...", path_str);
            match parser.parse_file(&path_str, &content) {
                Ok(doc) => {
                    if !doc.items.is_empty() {
                        modules.push(doc);
                    }
                }
                Err(e) => {
                    eprintln!("  Error parsing {}: {}", path_str, e);
                }
            }
        }
    }

    let project = ProjectDoc {
        name: "Peel Project".to_string(), // Could extract from a config file
        description: Some("Documentation generated by peeldoc.".to_string()),
        modules,
    };

    println!("Generating site in {}...", output_dir);
    let ssg = Ssg::new();
    ssg.generate(&project, output_dir).await?;

    println!("Success! Open {}/index.html to view documentation.", output_dir);

    Ok(())
}
