[project]

site_name = "Peel Language"

site_description = "The comprehensive guide and reference for the Peel programming language."

site_author = "The Peel Authors"

copyright = """
Copyright &copy; 2026 The Peel Authors
"""

nav = [
  { "Introduction" = "index.md" },
  { "Basics" = [
    { "Variables & Mutability" = "basics/variables.md" },
    { "Data Types" = "basics/types.md" },
    { "Control Flow" = "basics/control_flow.md" },
    { "Functions" = "basics/functions.md" },
  ]},
  { "Advanced" = [
    { "Structs & Enums" = "advanced/structs_enums.md" },
    { "Pattern Matching" = "advanced/pattern_matching.md" },
    { "Concurrency" = "advanced/concurrency.md" },
  ]},
  { "Standard Library" = [
    { "Console (`fmt`)" = "std/console.md" },
    { "Math" = "std/math.md" },
    { "JSON" = "std/json.md" },
  ]},
  { "Tooling" = [
    { "Package Manager (`pepm`)" = "tooling/pepm.md" },
  ]}
]

[project.theme]

language = "en"

features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
